### ISSUE TITLE
date range in 'year' column

### ISSUE THREAD

**Issue by semio** [semio/ddf--gapminder--hist_maternal_mort#1]
in the `year` column, the data type is mixed. There are:
1. a range of years (e.g. 1890-1900)
2. one year (e.g. 1905)

need to find a way to handle the range of years data.

**Comment by semio** [comment]
solution from jasper:

compare it to the data in Gapminder World and see how it was solved for that dataset

**Comment by semio** [comment]
found in GW

 the year in the middle of range is used. so 1856-60 becomes 1958

**Comment by semio** [comment]
PS: I think the year '1871-1980' is a mistake

**Comment by olarosling** [comment]
Please use the value for the mid-year of the period. Another alternative is to use it for all the years in the interval, but in a line-chart that would result in strange stairs-steps.
